/**
 * Ramat Gan Stadium — source of truth for SVG path IDs vs display names vs database IDs.
 * Geometry paths in ramatGanStadiumGeometry.generated.js use svgPathId as their `id`.
 */
export const STADIUM_CONFIG = [
  { svgPathId: '6A', displayName: '6A', dbId: '6A' },
  { svgPathId: '6C', displayName: '6C', dbId: '6C' },
  { svgPathId: 'B5', displayName: 'B5', dbId: 'B5' },
  { svgPathId: '13A', displayName: '13A', dbId: '13A' },
  { svgPathId: '13B', displayName: '13B', dbId: '13B' },
  { svgPathId: '13C', displayName: '13C', dbId: '13C' },
  { svgPathId: '6B', displayName: '6B', dbId: '6B' },
  { svgPathId: 'ACCESSIBLE', displayName: 'ACCESSIBLE', dbId: 'ACCESSIBLE' },
  { svgPathId: '16A', displayName: '16A', dbId: '16A' },
  { svgPathId: '16B', displayName: '16B', dbId: '16B' },
  { svgPathId: '11B', displayName: '11B', dbId: '11B' },
  { svgPathId: 'D12', displayName: 'D12', dbId: 'D12' },
  { svgPathId: 'A3', displayName: 'A3', dbId: 'A3' },
  { svgPathId: 'A2', displayName: 'A2', dbId: 'A2' },
  { svgPathId: 'A1', displayName: 'A1', dbId: 'A1' },
  { svgPathId: 'B4', displayName: 'B4', dbId: 'B4' },
  { svgPathId: '11A', displayName: '11A', dbId: '11A' },
  { svgPathId: 'B6', displayName: 'B6', dbId: 'B6' },
  { svgPathId: 'C7', displayName: 'C7', dbId: 'C7' },
  { svgPathId: 'C8', displayName: 'C8', dbId: 'C8' },
  { svgPathId: 'C9', displayName: 'C9', dbId: 'C9' },
  { svgPathId: '9A', displayName: '9A', dbId: '9A' },
  { svgPathId: 'D14', displayName: 'D14', dbId: 'D14' },
  { svgPathId: 'D13', displayName: 'D13', dbId: 'D13' },
  { svgPathId: 'D11', displayName: 'D11', dbId: 'D11' },
  { svgPathId: 'D10', displayName: 'D10', dbId: 'D10' },
  { svgPathId: '9B', displayName: '9B', dbId: '9B' },
  { svgPathId: 'STAGE', displayName: 'STAGE', dbId: 'STAGE' },
  { svgPathId: '4', displayName: '4', dbId: '4' },
  { svgPathId: '3', displayName: '3', dbId: '3' },
  { svgPathId: '2-3', displayName: '2-3', dbId: '2-3' },
  { svgPathId: '2', displayName: '2', dbId: '2' },
  { svgPathId: '1', displayName: '1', dbId: '1' },
];
