"""
Django settings for safeticket project.

Generated by 'django-admin startproject' using Django 4.2.27.
"""

from pathlib import Path
import json
import logging
import os
from decimal import Decimal
from urllib.parse import unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

_logger = logging.getLogger('safeticket.cloudinary')


def _env_origin_list(env_key, default):
    """
    Parse comma-separated origins for CORS/CSRF. Strips whitespace, trailing slashes,
    and supports ';' as separator (common copy/paste). Browser Origin never includes a trailing /.
    """
    raw = os.environ.get(env_key, default)
    out = []
    seen = set()
    for chunk in raw.replace(';', ',').split(','):
        o = chunk.strip().rstrip('/')
        if o and o not in seen:
            seen.add(o)
            out.append(o)
    return out


def _merge_unique_origins(base_list, *extras):
    seen = set(base_list)
    out = list(base_list)
    for raw in extras:
        if raw is None or raw == '':
            continue
        o = str(raw).strip().rstrip('/')
        if o and o not in seen:
            seen.add(o)
            out.append(o)
    return out


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dummy-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=true in .env only for local dev. On Render, leave unset or false so errors are not leaked.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# Platform commission rates (Decimal). Buyer fee is added at checkout; seller fee is withheld from payout.
PLATFORM_BUYER_SERVICE_FEE_RATE = Decimal(
    str(os.environ.get('PLATFORM_BUYER_SERVICE_FEE_RATE', '0.10'))
)
PLATFORM_SELLER_SERVICE_FEE_RATE = Decimal(
    str(os.environ.get('PLATFORM_SELLER_SERVICE_FEE_RATE', '0.05'))
)

# When True: looser PDF MIME checks (%PDF magic bytes), non-strict PyPDF, optional fallbacks for testing.
# Set RELAX_PDF_UPLOAD_VALIDATION=true on Render only while testing uploads; turn off for production.
RELAX_PDF_UPLOAD_VALIDATION = os.environ.get('RELAX_PDF_UPLOAD_VALIDATION', 'False').lower() in (
    'true',
    '1',
    'yes',
)

# External media (Cloudinary) — avoids lost uploads on Render's ephemeral disk.
# Set CLOUDINARY_URL (recommended) or CLOUDINARY_CLOUD_NAME + CLOUDINARY_API_KEY + CLOUDINARY_API_SECRET.
# Use one consistent source: mixed/stale split vars + a different CLOUDINARY_URL causes signature failures
# and uploads that never persist. After changing keys in the Cloudinary dashboard, update Render env in sync.
#
# IMPORTANT: only enable when credentials are *complete*. A lone CLOUDINARY_CLOUD_NAME (common partial
# dashboard state) previously set USE_CLOUDINARY=True and then ImproperlyConfigured at import — breaking
# migrate/collectstatic on Render (build exit 1).
_cld_url_set = bool((os.environ.get('CLOUDINARY_URL') or '').strip())
_cld_split_complete = all(
    bool((os.environ.get(k) or '').strip())
    for k in ('CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET')
)
USE_CLOUDINARY = _cld_url_set or _cld_split_complete

# Host header must match for Django to serve the request; mismatch -> fast 400 (DisallowedHost), not a hang.
# Not involved in TLS redirects (that would be SECURE_SSL_REDIRECT + proxy headers).
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'ALLOWED_HOSTS',
        'safeticket-api.onrender.com,localhost,127.0.0.1',
    ).split(',')
    if h.strip()
]


# Application definition
# cloudinary_storage after django.contrib.staticfiles so collectstatic uses WhiteNoise without
# Cloudinary intercepting static; STATICFILES_STORAGE below satisfies django-cloudinary-storage fallbacks.

_INSTALLED_CORE = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
if USE_CLOUDINARY:
    _INSTALLED_CORE += ['cloudinary_storage', 'cloudinary']
INSTALLED_APPS = _INSTALLED_CORE + [
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'users',
]

MIDDLEWARE = [
    'safeticket.middleware.GlobalExceptionJSONMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # First: CORS headers on all responses (before Whitenoise/Common)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'safeticket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'safeticket.wsgi.application'


# Database - Postgres via DATABASE_URL on Render; SQLite locally.
# CONN_MAX_AGE=0: no persistent connections (avoids workers blocking on stale DB conns after idle/sleep).
import dj_database_url

_db_config = dj_database_url.config(conn_max_age=0, conn_health_checks=True)
if _db_config:
    _db_config['CONN_MAX_AGE'] = 0
    # Fail fast when hostname/port is wrong (otherwise the deploy can hang until health check timeout).
    _engine = (_db_config.get('ENGINE') or '').lower()
    if 'postgresql' in _engine:
        _opts = _db_config.setdefault('OPTIONS', {})
        _opts.setdefault('connect_timeout', 15)

# On Render, never silently fall back to SQLite — that masks a missing DB link and breaks production.
_on_render = (os.environ.get('RENDER', '') or '').lower() == 'true'
if _on_render and not _db_config:
    raise ImproperlyConfigured(
        'DATABASE_URL is not set. In the Render dashboard: open your web service → Environment → '
        'ensure Postgres is linked (or paste the Internal Database URL as DATABASE_URL). '
        'After creating or replacing a database instance, update this value and redeploy.'
    )

DATABASES = {
    'default': _db_config if _db_config else {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# Custom User Model
AUTH_USER_MODEL = 'users.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Set to Israel timezone to preserve exact times entered by users
TIME_ZONE = 'Asia/Jerusalem'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Vite output from ../frontend/dist (built by build_render.sh before collectstatic on Render).
STATICFILES_DIRS = []
_frontend_dist = BASE_DIR.parent / 'frontend' / 'dist'
if _frontend_dist.is_dir():
    STATICFILES_DIRS.append(_frontend_dist)

# Media files (user uploaded files like PDFs)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
if not USE_CLOUDINARY:
    os.makedirs(MEDIA_ROOT, exist_ok=True)

# Populated below. On Cloudinary, credentials + cloudinary.config() run before STORAGES so
# MediaCloudinaryStorage / RawMediaCloudinaryStorage see a fully configured SDK (avoids admin upload quirks).
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}
CLOUDINARY_STORAGE = {}

if USE_CLOUDINARY:
    # django-cloudinary-storage/app_settings.py expects CLOUDINARY_STORAGE to include CLOUD_NAME, API_KEY,
    # API_SECRET (or it only sets `secure` and leaves SDK half-configured). Combined with pycloudinary
    # loading CLOUDINARY_CLOUD_NAME before CLOUDINARY_URL, that caused "Invalid Signature" on upload.
    #
    # Credential priority (Render often has both CLOUDINARY_URL and split vars; they can drift):
    # 1) If CLOUDINARY_CLOUD_NAME + CLOUDINARY_API_KEY + CLOUDINARY_API_SECRET are all non-empty → use them
    #    (fixes stale CLOUDINARY_URL while split keys were updated in the dashboard).
    # 2) Else parse CLOUDINARY_URL (and temporarily drop split env vars during first import only).
    # 3) Else ImproperlyConfigured.
    _split_cn = (os.environ.get('CLOUDINARY_CLOUD_NAME') or '').strip()
    _split_key = (os.environ.get('CLOUDINARY_API_KEY') or '').strip()
    _split_secret = (os.environ.get('CLOUDINARY_API_SECRET') or '').strip()
    _has_split = bool(_split_cn and _split_key and _split_secret)

    _cld_url = (os.environ.get('CLOUDINARY_URL') or '').strip().strip('"').strip("'")
    if _cld_url.startswith('\ufeff'):
        _cld_url = _cld_url.lstrip('\ufeff')

    _cred_from_url = False
    if _has_split:
        _cn, _key, _secret = _split_cn, _split_key, _split_secret
        _logger.info(
            'Cloudinary: using split CLOUDINARY_* (all set; overrides CLOUDINARY_URL for signing; cloud_name=%s)',
            _cn,
        )
    elif _cld_url:
        _cred_from_url = True
        _parsed = urlparse(_cld_url)
        if (_parsed.scheme or '').lower() != 'cloudinary':
            raise ValueError(
                'CLOUDINARY_URL must use the cloudinary:// scheme (e.g. cloudinary://api_key:api_secret@cloud_name)'
            )
        _cn = (_parsed.hostname or '').strip()
        _key = unquote(_parsed.username or '').strip()
        _secret = unquote(_parsed.password or '').strip()
        _logger.info(
            'Cloudinary: using CLOUDINARY_URL (cloud_name=%s, api_key=%s…)',
            _cn,
            (_key[:6] + '…') if len(_key) > 6 else '(set)',
        )
    else:
        _cn = _split_cn
        _key = _split_key
        _secret = _split_secret
        _logger.info(
            'Cloudinary: partial split env (cloud_name=%s)',
            _cn or '(empty)',
        )

    if not _cn or not _key or not _secret:
        raise ImproperlyConfigured(
            'Cloudinary is enabled but credentials are incomplete. Set CLOUDINARY_URL '
            '(cloudinary://API_KEY:API_SECRET@CLOUD_NAME) or CLOUDINARY_CLOUD_NAME, '
            'CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET.'
        )

    # Default sha1 (Cloudinary upload API historically uses SHA-1; set CLOUDINARY_SIGNATURE_ALGORITHM=sha256 if needed).
    _sig_alg_raw = (os.environ.get('CLOUDINARY_SIGNATURE_ALGORITHM') or 'sha1').strip().lower()
    if _sig_alg_raw not in ('sha1', 'sha256'):
        raise ImproperlyConfigured(
            'CLOUDINARY_SIGNATURE_ALGORITHM must be sha1 or sha256 (default sha1).'
        )

    # pycloudinary.Config() reads env on first import. If CLOUDINARY_CLOUD_NAME is set, it loads
    # every CLOUDINARY_* var and ignores CLOUDINARY_URL — stale split vars + correct URL → Invalid Signature.
    # Only strip split env during URL-only credential resolution so URL parse is the single source of truth.
    _saved_cld_split_env = {}
    if _cred_from_url:
        for _ek in ('CLOUDINARY_CLOUD_NAME', 'CLOUDINARY_API_KEY', 'CLOUDINARY_API_SECRET'):
            if _ek in os.environ:
                _saved_cld_split_env[_ek] = os.environ.pop(_ek)

    import cloudinary
    from cloudinary import utils as _cloudinary_utils

    for _ek, _ev in _saved_cld_split_env.items():
        os.environ[_ek] = _ev

    _sig_alg = (
        _cloudinary_utils.SIGNATURE_SHA256 if _sig_alg_raw == 'sha256' else _cloudinary_utils.SIGNATURE_SHA1
    )

    CLOUDINARY_STORAGE = {
        'SECURE': True,
        'CLOUD_NAME': _cn,
        'API_KEY': _key,
        'API_SECRET': _secret,
    }

    cloudinary.config(
        cloud_name=_cn,
        api_key=_key,
        api_secret=_secret,
        secure=True,
        signature_algorithm=_sig_alg,
    )

    STORAGES = {
        # Images (Artist, Event, User profile): resource_type=image uploads
        'default': {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'},
        # Ticket PDFs only: resource_type=raw (required — image storage rejects PDFs)
        'ticket_pdfs': {'BACKEND': 'cloudinary_storage.storage.RawMediaCloudinaryStorage'},
        'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
    }

# Larger payloads for admin/API image uploads (django-cloudinary-storage POSTs to Cloudinary)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', str(12 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('FILE_UPLOAD_MAX_MEMORY_SIZE', str(12 * 1024 * 1024)))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
# SessionAuthentication enforces CSRF; removed for JWT-only API (avoids 403 on cross-origin login)
REST_FRAMEWORK = {
    # Single entry: JWTCookieAuthentication subclasses JWT (header) + HttpOnly cookie; avoids double
    # registration where the stock JWTAuthentication 401s on stale Bearer before cookie fallback.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.JWTCookieAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/hour',
        'user': '2000/hour',
        'auth_login': '30/minute',
        'auth_register': '20/minute',
        'offers': '25/minute',
        'offers_mutations': '90/minute',
        'checkout': '60/minute',
        'checkout_reserve': '120/minute',
    },
}

# Simple JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS / CSRF origins — exact SPA origins (no trailing slash).
# Default production allows both the static Render site and the Django-served SPA on the API host
# (same machine: build_render.sh → Vite → collectstatic). Override via CORS_ALLOWED_ORIGINS / CSRF_TRUSTED_ORIGINS in dashboard.
CORS_ALLOW_ALL_ORIGINS = False
# Required for cross-origin XHR to send Accept-Credentials cookies (csrf, jwt cookies on API host).
CORS_ALLOW_CREDENTIALS = True
# Allow SPA scripts to read filenames on ticket blob downloads (extension / saved name).
CORS_EXPOSE_HEADERS = ['Content-Disposition']
_RENDER_WEB_ORIGIN = 'https://safeticket-web.onrender.com'
_RENDER_API_ORIGIN = 'https://safeticket-api.onrender.com'
_FRONTEND_FROM_ENV = os.environ.get('FRONTEND_ORIGIN', '').strip().rstrip('/')
if DEBUG:
    CORS_ALLOWED_ORIGINS = _env_origin_list(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173',
    )
    CSRF_TRUSTED_ORIGINS = _env_origin_list(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173',
    )
    if _FRONTEND_FROM_ENV:
        CORS_ALLOWED_ORIGINS = _merge_unique_origins(
            CORS_ALLOWED_ORIGINS, _FRONTEND_FROM_ENV
        )
        CSRF_TRUSTED_ORIGINS = _merge_unique_origins(
            CSRF_TRUSTED_ORIGINS, _FRONTEND_FROM_ENV
        )
else:
    CORS_ALLOWED_ORIGINS = _env_origin_list(
        'CORS_ALLOWED_ORIGINS',
        f'{_RENDER_WEB_ORIGIN},{_RENDER_API_ORIGIN}',
    )
    CSRF_TRUSTED_ORIGINS = _env_origin_list(
        'CSRF_TRUSTED_ORIGINS',
        f'{_RENDER_WEB_ORIGIN},{_RENDER_API_ORIGIN}',
    )
    # Always trust the SPA origin: env FRONTEND_ORIGIN or the known Render web URL (lists stay aligned).
    _fe_trust = _FRONTEND_FROM_ENV or _RENDER_WEB_ORIGIN
    CORS_ALLOWED_ORIGINS = _merge_unique_origins(CORS_ALLOWED_ORIGINS, _fe_trust)
    CSRF_TRUSTED_ORIGINS = _merge_unique_origins(CSRF_TRUSTED_ORIGINS, _fe_trust)

# Always merge canonical browser origins — not only when RENDER env is set.
# DEBUG=True on the API previously combined with missing RENDER allowed only localhost CORS; the SPA
# then saw "blocked by CORS" (same symptom as a 502 with no ACAO header).
CORS_ALLOWED_ORIGINS = _merge_unique_origins(
    CORS_ALLOWED_ORIGINS,
    _RENDER_WEB_ORIGIN,
    _RENDER_API_ORIGIN,
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    *([_FRONTEND_FROM_ENV] if _FRONTEND_FROM_ENV else []),
)
CSRF_TRUSTED_ORIGINS = _merge_unique_origins(
    CSRF_TRUSTED_ORIGINS,
    _RENDER_WEB_ORIGIN,
    _RENDER_API_ORIGIN,
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    *([_FRONTEND_FROM_ENV] if _FRONTEND_FROM_ENV else []),
)

# Explicit production origins (defense in depth if env lists are truncated).
CSRF_TRUSTED_ORIGINS = _merge_unique_origins(
    CSRF_TRUSTED_ORIGINS,
    'https://safeticket-web.onrender.com',
    'https://safeticket-api.onrender.com',
)
CORS_ALLOWED_ORIGINS = _merge_unique_origins(
    CORS_ALLOWED_ORIGINS,
    'https://safeticket-web.onrender.com',
    'https://safeticket-api.onrender.com',
)

# JWT HttpOnly cookie names
JWT_ACCESS_COOKIE_NAME = 'access_token'
JWT_REFRESH_COOKIE_NAME = 'refresh_token'

# Email — SMTP when host + credentials are set; otherwise console (local dev).
# Render / production: set all of EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, DEFAULT_FROM_EMAIL.
# Examples:
#   Resend SMTP: EMAIL_HOST=smtp.resend.com  EMAIL_PORT=587  EMAIL_USE_TLS=true
#                EMAIL_HOST_USER=resend  EMAIL_HOST_PASSWORD=<api_key>
#                DEFAULT_FROM_EMAIL="TradeTix <onboarding@yourdomain.com>" (verified sender)
#   SendGrid: EMAIL_HOST=smtp.sendgrid.net  EMAIL_PORT=587  EMAIL_USE_TLS=true
#             EMAIL_HOST_USER=apikey  EMAIL_HOST_PASSWORD=<api_key>
# Port 465: set EMAIL_USE_SSL=true and EMAIL_USE_TLS=false
# Override backend explicitly: EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
_email_host = (os.environ.get('EMAIL_HOST') or '').strip()
_email_user = (os.environ.get('EMAIL_HOST_USER') or '').strip()
_email_password = (os.environ.get('EMAIL_HOST_PASSWORD') or '').strip()
_email_backend_override = (os.environ.get('EMAIL_BACKEND') or '').strip()
if _email_backend_override:
    EMAIL_BACKEND = _email_backend_override
elif _email_host and _email_user and _email_password:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = _email_host or 'localhost'
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = _email_user
EMAIL_HOST_PASSWORD = _email_password
DEFAULT_FROM_EMAIL = (os.environ.get('DEFAULT_FROM_EMAIL') or 'noreply@tradetix.local').strip()
SERVER_EMAIL = (os.environ.get('SERVER_EMAIL') or DEFAULT_FROM_EMAIL).strip()
# Cap SMTP blocking (e.g. Resend) so hung connections fail fast; override via EMAIL_TIMEOUT env if needed.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '5'))


def _fx_rate_to_ils(env_key: str, default: str) -> Decimal:
    """Indicative rates for admin dashboard ILS rollups only (not payment quotes)."""
    return Decimal(str(os.environ.get(env_key, default)))


# 1 unit foreign currency → ILS. Override in production via FX_USD_ILS, FX_EUR_ILS, FX_GBP_ILS.
FX_RATES_TO_ILS = {
    'ILS': Decimal('1'),
    'USD': _fx_rate_to_ils('FX_USD_ILS', '3.65'),
    'EUR': _fx_rate_to_ils('FX_EUR_ILS', '3.95'),
    'GBP': _fx_rate_to_ils('FX_GBP_ILS', '4.65'),
}

# Public origins for buyer receipt emails (no trailing slash). On Render set both explicitly.
API_PUBLIC_ORIGIN = os.environ.get('API_PUBLIC_ORIGIN', 'http://127.0.0.1:8000').rstrip('/')

# Payme.io — keys from environment only (sandbox: PAYME_GENERATE_SALE_URL test host).
PAYME_MERCHANT_ID = (os.environ.get('PAYME_MERCHANT_ID') or '').strip()
PAYME_API_KEY = (os.environ.get('PAYME_API_KEY') or '').strip()
PAYME_API_SECRET = (os.environ.get('PAYME_API_SECRET') or '').strip()
PAYME_GENERATE_SALE_URL = (
    os.environ.get('PAYME_GENERATE_SALE_URL') or 'https://testpay.payme.io/api/generate-sale'
).strip()
PAYME_WEBHOOK_SECRET = (os.environ.get('PAYME_WEBHOOK_SECRET') or '').strip()
PAYME_SUB_SELLER_PAYEE_ID = (os.environ.get('PAYME_SUB_SELLER_PAYEE_ID') or '').strip()
try:
    PAYME_EXTRA_BODY_JSON = json.loads(os.environ.get('PAYME_EXTRA_BODY_JSON', '{}') or '{}')
except json.JSONDecodeError:
    PAYME_EXTRA_BODY_JSON = {}

FRONTEND_ORIGIN = (
    _FRONTEND_FROM_ENV
    if _FRONTEND_FROM_ENV
    else ('http://localhost:3000' if DEBUG else _RENDER_WEB_ORIGIN)
).rstrip('/')
# Transactional templates: users/templates/emails/*.html (+ .txt); sent via users.notifications.

# Cache for OTP storage (10 min TTL)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Production security headers (proxy + cross-origin cookies on Render)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# False: Render terminates TLS; Django must not 301 to https:// (would loop or confuse the edge proxy).
SECURE_SSL_REDIRECT = False
# So request.get_host() matches the public hostname (helps CSRF Origin / cookie scoping behind the proxy).
USE_X_FORWARDED_HOST = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Cross-site cookies (SPA safeticket-web.onrender.com ↔ API safeticket-api.onrender.com).
# Mobile Safari / ITP: CSRF + session cookies MUST be SameSite=None; Secure=True on HTTPS API
# or the browser will not attach them on credentialed XHR/fetch from the static site origin.
# Render sets RENDER=yes — force None+Secure even if DEBUG were mis-set (avoids silent CSRF 403 on checkout).
# Local HTTP: Lax unless SAFETICKET_CROSS_SITE_COOKIES=1 (HTTPS dev tunnel).
_RENDER_SERVICE = bool((os.environ.get('RENDER') or '').strip())
_FORCE_CROSS_SITE = os.environ.get('SAFETICKET_CROSS_SITE_COOKIES', '').lower() in ('1', 'true', 'yes')
if DEBUG and not _FORCE_CROSS_SITE and not _RENDER_SERVICE:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SAMESITE = 'Lax'
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SAMESITE = 'None'

# When True, login/register return JWT in JSON so mobile Safari can use Authorization: Bearer (cookies often blocked on cross-origin XHR).
# Set JWT_RESPONSE_BODY_TOKENS=false only for legacy same-site dev without bearer storage.
JWT_RESPONSE_BODY_TOKENS = os.environ.get(
    'JWT_RESPONSE_BODY_TOKENS',
    'true',
).lower() in ('1', 'true', 'yes')

CSRF_COOKIE_PATH = '/'
SESSION_COOKIE_PATH = '/'
# False: token is mirrored in JSON for X-CSRFToken; cookie must still be stored/sent for Django's CSRF check.
CSRF_COOKIE_HTTPONLY = False

# Legacy fallback: Django 4.2+ uses STORAGES['staticfiles']; django-cloudinary-storage collectstatic
# still accesses settings.STATICFILES_STORAGE — must exist on django.conf.settings (Django 6 has no default).
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
