# Generated by Django 6.0 on 2025-12-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ticket_id',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('seat_row', models.CharField(blank=True, help_text='Optional seat/row information', max_length=100, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Face value of the ticket', max_digits=10)),
                ('asking_price', models.DecimalField(decimal_places=2, help_text='Price seller is asking for', max_digits=10)),
                ('pdf_file', models.FileField(help_text='Upload the PDF ticket file', upload_to='tickets/pdfs/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending_payout', 'Pending Payout'), ('paid_out', 'Paid Out')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='users_ticke_status_439fae_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['seller', 'status'], name='users_ticke_seller__8f7337_idx'),
        ),
    ]
