# Generated by Django 6.0 on 2025-12-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_order_ticket_id_ticket_order_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, help_text='Price (always equals original_price per Israeli law)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='original_price',
            field=models.DecimalField(decimal_places=2, help_text='Face value of the ticket (final price)', max_digits=10),
        ),
    ]
