# Generated by Django 6.0 on 2025-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_available_quantity_to_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(help_text='Upload the PDF ticket file (can contain multiple tickets)', upload_to='tickets/pdfs/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_row',
            field=models.CharField(blank=True, help_text='Optional seat/row information (legacy field)', max_length=100, null=True),
        ),
    ]
