# Generated by Django 6.0 on 2025-12-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_reservation_fields_to_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Legacy field - use event.date instead', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(blank=True, help_text='Legacy field - use event.name instead', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='venue',
            field=models.CharField(blank=True, help_text='Legacy field - use event.venue instead', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name', max_length=255)),
                ('date', models.DateTimeField(help_text='Event date and time')),
                ('venue', models.CharField(help_text='Venue name', max_length=255)),
                ('city', models.CharField(help_text='City where event takes place', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Event image/photo', null=True, upload_to='events/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'name'],
                'indexes': [models.Index(fields=['-date', 'name'], name='users_event_date_c58bc6_idx'), models.Index(fields=['city'], name='users_event_city_c42317_idx')],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The event this ticket is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='users.event'),
        ),
    ]
