# Generated by Django 6.0 on 2025-12-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_ticket_event_date_alter_ticket_event_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Artist name', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Artist image/photo', null=True, upload_to='artists/images/')),
                ('description', models.TextField(blank=True, help_text='Artist description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='users_artis_name_72182f_idx')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='The artist/performer for this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.artist'),
        ),
    ]
