# Generated by Django 6.0 on 2026-01-01 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_artist_event_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to notify when tickets become available', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False, help_text='Whether this alert has been sent')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True)),
                ('event', models.ForeignKey(help_text='The event to be notified about', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'notified'], name='users_ticke_event_i_a1bdaf_idx')],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
