# Generated by Django 6.0 on 2026-01-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_ticketalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='row_number',
            field=models.CharField(blank=True, help_text='Specific row number for this individual ticket', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Specific seat number for this individual ticket', max_length=50, null=True),
        ),
    ]
