# Generated by Django 6.0 on 2026-01-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_ticket_row_number_ticket_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='listing_group_id',
            field=models.CharField(blank=True, help_text='UUID to group tickets from the same listing session', max_length=100, null=True),
        ),
    ]
