# Generated by Django 6.0 on 2026-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_ticket_listing_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times this event page has been viewed (for popularity tracking)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='delivery_method',
            field=models.CharField(choices=[('instant', 'Instant Download'), ('mobile', 'Mobile Transfer'), ('physical', 'Physical')], default='instant', help_text='How the ticket will be delivered to buyer', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_seller',
            field=models.BooleanField(default=False, help_text='Verified seller badge (for trust indicators)'),
        ),
    ]
