# Generated by Django 6.0 on 2026-01-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_event_view_count_ticket_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('pending_payout', 'Pending Payout'), ('paid_out', 'Paid Out'), ('rejected', 'Rejected')], default='pending_verification', max_length=20),
        ),
    ]
