# Generated by Django 6.0 on 2026-03-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_pending_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The offer amount (bid price)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('expired', 'Expired')], default='pending', help_text='Current status of the offer', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When the offer expires (48 hours from creation)')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the offer was accepted', null=True)),
                ('checkout_expires_at', models.DateTimeField(blank=True, help_text='When the checkout window expires (4 hours after acceptance)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='The buyer making the offer', on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
                ('counter_offer', models.ForeignKey(blank=True, help_text='If this is a counter-offer, link to the original offer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_offer', to='users.offer')),
                ('ticket', models.ForeignKey(help_text='The ticket being offered on', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='users.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', 'status'], name='users_offer_buyer_i_c72a35_idx'), models.Index(fields=['ticket', 'status'], name='users_offer_ticket__aaea79_idx'), models.Index(fields=['status', 'expires_at'], name='users_offer_status_f6e8b2_idx'), models.Index(fields=['checkout_expires_at'], name='users_offer_checkou_228ceb_idx')],
            },
        ),
    ]
