# Generated by Django 6.0 on 2026-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_quantity_to_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(choices=[('מנורה מבטחים', 'מנורה מבטחים'), ('בלומפילד', 'בלומפילד'), ('סמי עופר', 'סמי עופר'), ('בארבי תל אביב', 'בארבי תל אביב'), ('אחר', 'אחר')], default='מנורה מבטחים', help_text='Venue name', max_length=255),
        ),
    ]
