# Generated by Django 6.0 on 2026-03-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Artist cover/banner image', null=True, upload_to='artist_covers/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, help_text='Genre (e.g., Pop, Rock, Sports)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_link',
            field=models.URLField(blank=True, help_text='Spotify artist page link', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='YouTube channel or video link', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(choices=[('ללא הגבלה', 'ללא הגבלה'), ('18+', '18+'), ('21+', '21+')], default='ללא הגבלה', help_text='Age restriction for the event', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('הופעה', 'הופעה'), ('הצגה', 'הצגה'), ('ספורט', 'ספורט'), ('פסטיבל', 'פסטיבל'), ('סטנדאפ', 'סטנדאפ')], default='הופעה', help_text='Event category', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='doors_open',
            field=models.TimeField(blank=True, help_text='Time when doors open', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('פעיל', 'פעיל'), ('בוטל', 'בוטל'), ('נדחה', 'נדחה'), ('סולד אאוט', 'סולד אאוט')], default='פעיל', help_text='Event status', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_obstructed_view',
            field=models.BooleanField(default=False, help_text='Does this ticket have an obstructed view? (Important for buyer trust)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='split_type',
            field=models.CharField(choices=[('כל כמות', 'כל כמות'), ('זוגות בלבד', 'זוגות בלבד'), ('מכור הכל יחד', 'מכור הכל יחד')], default='כל כמות', help_text='How tickets can be split/sold', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('כרטיס אלקטרוני / PDF', 'כרטיס אלקטרוני / PDF'), ('העברה באפליקציה', 'העברה באפליקציה'), ('כרטיס נייר פיזי', 'כרטיס נייר פיזי')], default='כרטיס אלקטרוני / PDF', help_text='Type of ticket', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='verification_status',
            field=models.CharField(choices=[('ממתין לאישור', 'ממתין לאישור'), ('מאומת', 'מאומת'), ('נדחה', 'נדחה')], default='ממתין לאישור', help_text='Ticket verification status (admin approval required)', max_length=50),
        ),
    ]
