# Generated by Django 6.0 on 2026-03-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_artist_cover_image_artist_genre_artist_spotify_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact name', max_length=255)),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('order_number', models.CharField(blank=True, help_text='Optional order number reference', max_length=100, null=True)),
                ('message', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this message has been resolved')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='users_conta_is_reso_4085cd_idx'), models.Index(fields=['email'], name='users_conta_email_94d804_idx')],
            },
        ),
    ]
