# Generated by Django 6.0 on 2026-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_team',
            field=models.CharField(blank=True, help_text='Away team name (for sports events)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team',
            field=models.CharField(blank=True, help_text='Home team name (for sports events)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.CharField(blank=True, help_text='Tournament/League name (e.g., Champions League, Premier League)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'Concert'), ('theater', 'Theater'), ('sport', 'Sport'), ('festival', 'Festival'), ('standup', 'Standup'), ('הופעה', 'הופעה'), ('הצגה', 'הצגה'), ('ספורט', 'ספורט'), ('פסטיבל', 'פסטיבל'), ('סטנדאפ', 'סטנדאפ')], default='concert', help_text='Event category', max_length=50),
        ),
    ]
