# Generated by Django 6.0 on 2026-03-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_event_away_team_event_home_team_event_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('concert', 'הופעות'), ('sport', 'משחקי ספורט'), ('theater', 'הצגות תיאטרון'), ('festival', 'פסטיבלים'), ('standup', 'סטנדאפ')], default='concert', help_text='Event category', max_length=50),
        ),
    ]
