# Generated by Django 6.0 on 2026-03-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_round_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=initial buyer offer, 1=seller counter, 2=buyer counter (max)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='parent_offer',
            field=models.ForeignKey(blank=True, help_text='The previous offer in this negotiation chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='users.offer'),
        ),
    ]
