# Generated by Django 6.0.1 on 2026-03-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_add_is_email_verified_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticket_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of ticket IDs in this order'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=True, help_text='Email verified via OTP (False when OTP enforcement is enabled)'),
        ),
    ]
