# Generated by Django 6.0.1 on 2026-03-27 15:06

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def backfill_escrow_payout(apps, schema_editor):
    Order = apps.get_model('users', 'Order')
    for order in Order.objects.filter(status__in=['paid', 'completed']).iterator():
        ticket = order.ticket
        if not ticket:
            continue
        event_dt = None
        try:
            if ticket.event_id:
                ev = ticket.event
                if ev:
                    event_dt = ev.date
        except Exception:
            event_dt = None
        if event_dt is None:
            event_dt = ticket.event_date
        if event_dt is None:
            continue
        if timezone.is_naive(event_dt):
            event_dt = timezone.make_aware(event_dt, timezone.get_current_timezone())
        ped = event_dt + timedelta(hours=24)
        order.payout_eligible_date = ped
        order.payout_status = 'locked'
        if ped <= timezone.now():
            order.payout_status = 'eligible'
        order.save(update_fields=['payout_eligible_date', 'payout_status'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_order_price_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payout_eligible_date',
            field=models.DateTimeField(blank=True, help_text='When seller payout becomes eligible (24 hours after event start)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(choices=[('locked', 'Locked'), ('eligible', 'Eligible'), ('paid', 'Paid')], default='locked', help_text='Escrow lifecycle: locked → eligible (after event+24h) → paid', max_length=20),
        ),
        migrations.RunPython(backfill_escrow_payout, noop_reverse),
    ]
