# Generated by Django 6.0.1 on 2026-03-28 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_eventrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='held_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity subtracted from held_ticket.available_quantity for this pending order'),
        ),
        migrations.AddField(
            model_name='order',
            name='held_ticket',
            field=models.ForeignKey(blank=True, help_text='Ticket row with decremented available_quantity while order is pending_payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payment_holds', to='users.ticket'),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_offer',
            field=models.ForeignKey(blank=True, help_text='Negotiated offer associated with this checkout before payment confirms', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_orders', to='users.offer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
