# Generated by Django 6.0.1 on 2026-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_order_payment_confirm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_escrow_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='escrow_terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_details',
            field=models.TextField(blank=True, default='', help_text='PayPal email, bank transfer details, etc. (seller onboarding)'),
        ),
    ]
