# Generated by Django 6.0.1 on 2026-03-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_event_category_verbose'),
    ]

    operations = [
    ]
