# Generated by Django 6.0.1 on 2026-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_sync_for_render_deploy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(default='IL', help_text='Event jurisdiction for pricing and proof-of-purchase rules (e.g. IL, US, GB)', max_length=2),
        ),
        migrations.AddField(
            model_name='ticket',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Proof of purchase / receipt (mandatory for Israeli events)', null=True, upload_to='tickets/receipts/'),
        ),
    ]
