# Generated by Django 6.0.1 on 2026-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_rename_pending_verification_to_pending_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(choices=[('IL', 'Israel'), ('US', 'United States'), ('GB', 'United Kingdom'), ('ES', 'Spain'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('GR', 'Greece'), ('CY', 'Cyprus'), ('AE', 'United Arab Emirates')], default='IL', help_text='Event location country (anti-scalping rules use this field, not city).', max_length=2),
        ),
    ]
