# Generated by Django 6.0.1 on 2026-04-03 12:48

from django.db import migrations, models


def _iso4217(country):
    c = (country or 'IL').strip().upper() if country else 'IL'
    if c == 'IL':
        return 'ILS'
    if c == 'US':
        return 'USD'
    if c == 'GB':
        return 'GBP'
    if c in ('DE', 'FR', 'ES', 'IT', 'GR', 'CY'):
        return 'EUR'
    if c == 'AE':
        return 'USD'
    return 'ILS'


def backfill_offer_order_currency(apps, schema_editor):
    Offer = apps.get_model('users', 'Offer')
    Order = apps.get_model('users', 'Order')
    Ticket = apps.get_model('users', 'Ticket')
    Event = apps.get_model('users', 'Event')
    for o in Offer.objects.select_related('ticket').iterator():
        country = 'IL'
        if o.ticket_id:
            ev_id = Ticket.objects.filter(pk=o.ticket_id).values_list('event_id', flat=True).first()
            if ev_id:
                country = Event.objects.filter(pk=ev_id).values_list('country', flat=True).first() or 'IL'
        Offer.objects.filter(pk=o.pk).update(currency=_iso4217(country))
    for ord_row in Order.objects.select_related('ticket').iterator():
        c = 'ILS'
        if ord_row.ticket_id:
            ev_id = Ticket.objects.filter(pk=ord_row.ticket_id).values_list('event_id', flat=True).first()
            if ev_id:
                country = Event.objects.filter(pk=ev_id).values_list('country', flat=True).first()
                c = _iso4217(country)
        if ord_row.related_offer_id:
            off = Offer.objects.filter(pk=ord_row.related_offer_id).first()
            if off and getattr(off, 'currency', None):
                c = off.currency
        Order.objects.filter(pk=ord_row.pk).update(currency=c)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_event_country_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='When the show ends (optional). Escrow payout uses ends_at + 24h when set; else date + 24h.', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='currency',
            field=models.CharField(default='ILS', help_text='ISO 4217; locked to listing/event — no mixed-currency negotiation', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='ILS', help_text='ISO 4217; matches Event.country at listing time', max_length=3),
        ),
        migrations.RunPython(backfill_offer_order_currency, migrations.RunPython.noop),
    ]
