# Generated by Django 6.0.1 on 2026-04-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_order_seller_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='high_demand',
            field=models.BooleanField(
                default=False,
                help_text='Show high-demand urgency badge on discovery (e.g. official launch headliners).',
            ),
        ),
    ]
