# Generated by Django 6.0.1 on 2026-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_event_high_demand_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='checkout_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the checkout window expires (24 hours after acceptance)', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='10% buyer-side service fee (on top of final_negotiated_price)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_seller_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount seller receives after 5% seller_service_fee on final_negotiated_price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='section_legacy',
            field=models.CharField(blank=True, help_text='Legacy section label (e.g. Gate 11); kept for migrated rows and display fallback.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('כרטיס אלקטרוני / PDF', 'כרטיס אלקטרוני / PDF'), ('כרטיס אלקטרוני (PDF או תמונה)', 'כרטיס אלקטרוני (PDF או תמונה)'), ('העברה באפליקציה', 'העברה באפליקציה'), ('כרטיס נייר פיזי', 'כרטיס נייר פיזי')], default='כרטיס אלקטרוני (PDF או תמונה)', help_text='Type of ticket', max_length=50),
        ),
    ]
