# Generated by Django 6.0.1 on 2026-04-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_sync_model_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payme_status',
            field=models.CharField(blank=True, help_text='Last known Payme payment status (webhook / API)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payme_transaction_id',
            field=models.CharField(blank=True, help_text='Payme gateway transaction / sale id', max_length=120, null=True),
        ),
    ]
