# Generated by Django 6.0.1 on 2026-05-04 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_make_ticket_receipt_optional_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='15% buyer-side service fee (added on top of final_negotiated_price)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_seller_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount seller receives after seller_service_fee (currently 0%) on final_negotiated_price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0% seller-side platform fee — sellers keep 100% of their asking price', max_digits=10),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous browser session UUID (localStorage); no PII.', max_length=64)),
                ('path', models.CharField(help_text='URL path, e.g. /events/12', max_length=500)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('checkout_start', 'Checkout Start'), ('checkout_complete', 'Purchase Complete'), ('offer_submitted', 'Offer Submitted'), ('ticket_viewed', 'Ticket Viewed')], db_index=True, max_length=30)),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Optional extra context (event_id, ticket_id, etc.).')),
                ('ip_hash', models.CharField(blank=True, help_text='First 32 chars of SHA-256(client IP) — allows unique-visitor counts without storing raw PII.', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'event_type'], name='users_analy_timesta_90a7bf_idx'), models.Index(fields=['session_id', 'timestamp'], name='users_analy_session_0ac0aa_idx')],
            },
        ),
    ]
