# Generated by Django 6.0.1 on 2026-06-04 14:07

import json

import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def _backfill_seller_bank_and_payouts(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Order = apps.get_model('users', 'Order')
    Ticket = apps.get_model('users', 'Ticket')
    Payout = apps.get_model('users', 'Payout')

    for user in User.objects.exclude(payout_details='').iterator():
        raw = (user.payout_details or '').strip()
        if not raw:
            continue
        try:
            data = json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            continue
        if not isinstance(data, dict):
            continue
        updates = {}
        if not (user.account_holder_name or '').strip() and data.get('account_holder_name'):
            updates['account_holder_name'] = str(data['account_holder_name'])[:200]
        bank_src = data.get('bank_name') or data.get('bank_name_or_code')
        if not (user.bank_name or '').strip() and bank_src:
            updates['bank_name'] = str(bank_src)[:120]
        if not (user.branch_number or '').strip() and data.get('branch_number'):
            updates['branch_number'] = str(data['branch_number'])[:20]
        if not (user.account_number or '').strip() and data.get('account_number'):
            updates['account_number'] = str(data['account_number'])[:30]
        if updates:
            User.objects.filter(pk=user.pk).update(**updates)

    for order in Order.objects.filter(status__in=('paid', 'completed')).iterator():
        if Payout.objects.filter(order_id=order.pk).exists():
            continue
        ticket = None
        if order.ticket_id:
            ticket = Ticket.objects.filter(pk=order.ticket_id).select_related('seller').first()
        elif order.ticket_ids:
            ids = order.ticket_ids or []
            if ids:
                ticket = Ticket.objects.filter(pk=ids[0]).select_related('seller').first()
        if not ticket or not ticket.seller_id:
            continue
        total = order.total_paid_by_buyer or order.total_amount
        if total is None:
            continue
        buyer_fee = Decimal(order.buyer_service_fee or 0).quantize(Decimal('0.01'))
        seller_fee = Decimal(order.seller_service_fee or 0).quantize(Decimal('0.01'))
        commission = (buyer_fee + seller_fee).quantize(Decimal('0.01'))
        if order.net_seller_revenue is not None:
            net = Decimal(order.net_seller_revenue).quantize(Decimal('0.01'))
        else:
            net = (Decimal(total) - commission).quantize(Decimal('0.01'))
        Payout.objects.create(
            order_id=order.pk,
            seller_id=ticket.seller_id,
            total_sale_amount=Decimal(total).quantize(Decimal('0.01')),
            platform_commission=commission,
            net_payout=net,
            status='PENDING',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_fix_bloomfield_concert_events_and_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_holder_name',
            field=models.CharField(blank=True, default='', help_text='Legal name on the seller bank account (for manual payouts)', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default='', help_text='Bank account number for seller payouts', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Bank name or Israeli bank code', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_number',
            field=models.CharField(blank=True, default='', help_text='Bank branch number', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='payout_details',
            field=models.TextField(blank=True, default='', help_text='Legacy JSON blob from seller onboarding (see structured bank fields below)'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sale_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid by the buyer', max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, help_text='TRADETIX platform fees (buyer + seller service fees)', max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, help_text='Amount owed to the seller (total_sale_amount − platform_commission)', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seller_payout', to='users.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='users_payou_status_8a94a6_idx'), models.Index(fields=['seller', 'status'], name='users_payou_seller__a2e6c0_idx')],
            },
        ),
        migrations.RunPython(_backfill_seller_bank_and_payouts, migrations.RunPython.noop),
    ]
