# Generated by Django 6.0.1 on 2026-07-02 13:23

import django.core.files.storage
import pathlib
import users.secure_ticket_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_artist_category_local_market'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerpayout',
            new_name='users_selle_payout__b90e70_idx',
            old_name='users_seller_payout_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerpayout',
            new_name='users_selle_seller__e3dd84_idx',
            old_name='users_seller_payout_seller_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketalert',
            new_name='users_ticke_artist__9ca5c5_idx',
            old_name='users_ticke_artist__8a1f2d_idx',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(help_text='Upload the PDF ticket file (can contain multiple tickets)', storage=django.core.files.storage.FileSystemStorage(base_url='media/', location=pathlib.PureWindowsPath('C:/Users/user/Desktop/SafeTicket/backend/media')), upload_to=users.secure_ticket_storage.ticket_pdf_upload_to),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Optional proof of purchase / receipt file', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='media/', location=pathlib.PureWindowsPath('C:/Users/user/Desktop/SafeTicket/backend/media')), upload_to=users.secure_ticket_storage.ticket_receipt_upload_to),
        ),
    ]
