# Generated by Django 6.0.1 on 2026-07-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_order_guest_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bit_phone_number',
            field=models.CharField(blank=True, help_text='Bit payout phone number when payout_method=bit.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_method',
            field=models.CharField(choices=[('bank', 'Bank transfer'), ('bit', 'Bit')], default='bank', help_text='Preferred manual payout destination (bank or Bit).', max_length=10),
        ),
    ]
