# Generated by Django 6.0.1 on 2026-07-15 10:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_rename_venue_other_to_israel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affiliate_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Affiliate payout share of base (5% when coupon applied)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_fee_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of buyer fee waived by affiliate coupon (5% of base when applied)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_net_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform keep after affiliate split (15% without coupon; 5% with coupon)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Buyer-side service fee added on top of final_negotiated_price (base 15%, or 10% with affiliate coupon)', max_digits=10),
        ),
        migrations.CreateModel(
            name='AffiliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Default affiliate share of listing base when their coupon is used (0.05 = 5%)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Optional linked TradeTix user for payout attribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions_total', models.PositiveIntegerField(blank=True, help_text='Global cap across all users; null = unlimited', null=True)),
                ('buyer_discount_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Buyer saves this rate off listing base (fee drops from 15% → 10%)', max_digits=5)),
                ('affiliate_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5)),
                ('platform_net_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='users.affiliatepartner')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.coupon'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('buyer_key', models.CharField(db_index=True, help_text='Stable identity: user:<id> or guest:<email> — uniqueness anchor', max_length=180)),
                ('status', models.CharField(choices=[('pending', 'Pending checkout'), ('redeemed', 'Redeemed'), ('released', 'Released')], default='pending', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('affiliate_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('platform_net_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('buyer_fee_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='users.coupon')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemption', to='users.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coupon', 'status'], name='users_coupo_coupon__9d67aa_idx'), models.Index(fields=['buyer_key', 'status'], name='users_coupo_buyer_k_3ff78f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'redeemed'])), fields=('coupon', 'buyer_key'), name='users_couponredemption_unique_active_buyer')],
            },
        ),
    ]
