# Generated by Django 6.0.1 on 2026-07-15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_affiliate_coupon_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(
                choices=[('affiliate', 'Affiliate'), ('platform', 'Platform')],
                db_index=True,
                default='affiliate',
                help_text='affiliate = partner-owned; platform = TradeTix-owned (no affiliate commission)',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='affiliate',
            field=models.ForeignKey(
                blank=True,
                help_text='Required for affiliate coupons; must be null for platform coupons',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='coupons',
                to='users.affiliatepartner',
            ),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='affiliate_commission_rate',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0.0500'),
                help_text='Affiliate share of base; must be 0 for platform coupons',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='buyer_discount_rate',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0.0500'),
                help_text='Buyer saves this rate off listing base (fee drops from 15% by this amount)',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='platform_net_rate',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0.0500'),
                help_text='Platform keep of base when coupon applies (affiliate: 5%; platform coupon: typically 10%)',
                max_digits=5,
            ),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(('coupon_type', 'affiliate'), ('affiliate__isnull', False))
                    | models.Q(('coupon_type', 'platform'), ('affiliate__isnull', True))
                ),
                name='users_coupon_type_affiliate_fk_consistency',
            ),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(('coupon_type', 'platform'), _negated=True)
                    | models.Q(('affiliate_commission_rate', Decimal('0.0000')))
                ),
                name='users_coupon_platform_zero_affiliate_rate',
            ),
        ),
    ]
