# Generated by Django 6.0.1 on 2026-07-15

from decimal import Decimal

from django.db import migrations, models


def create_default_fee_settings(apps, schema_editor):
    GlobalFeeSettings = apps.get_model('users', 'GlobalFeeSettings')
    if not GlobalFeeSettings.objects.filter(pk=1).exists():
        GlobalFeeSettings.objects.create(
            pk=1,
            base_buyer_fee_percent=Decimal('12.00'),
            base_seller_fee_percent=Decimal('0.00'),
            buyer_coupon_discount_percent=Decimal('5.00'),
            affiliate_commission_percent=Decimal('5.00'),
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_platform_owned_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'base_buyer_fee_percent',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('12.00'),
                        help_text='Buyer service fee with no coupon (default 12%).',
                        max_digits=6,
                    ),
                ),
                (
                    'base_seller_fee_percent',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='Seller-side fee withheld from listing base (default 0%).',
                        max_digits=6,
                    ),
                ),
                (
                    'buyer_coupon_discount_percent',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('5.00'),
                        help_text='Fee reduction for the buyer when any coupon applies (default 5%).',
                        max_digits=6,
                    ),
                ),
                (
                    'affiliate_commission_percent',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('5.00'),
                        help_text='Affiliate share of listing base when an affiliate coupon applies (default 5%).',
                        max_digits=6,
                    ),
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global fee settings',
                'verbose_name_plural': 'Global fee settings',
            },
        ),
        migrations.RunPython(create_default_fee_settings, noop_reverse),
    ]
