# Generated by Django 6.0.1 on 2026-05-17 15:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0046_nuke_events_reseed_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds ready to withdraw or spend internally.', max_digits=10)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds held in escrow until the event ends / payout rules clear.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for event / release conditions'), ('PROCESSING', 'API call sent to PayMe'), ('COMPLETED', 'Successfully transferred'), ('FAILED', 'Transfer error')], db_index=True, default='PENDING', max_length=20)),
                ('payme_batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payme_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='users.event')),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='wallets.userwallet')),
                ('sender_wallet', models.ForeignKey(blank=True, help_text='Null when funds originate from the platform treasury (not a user wallet row).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='wallets.userwallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wallets_wal_status_978b0a_idx')],
            },
        ),
    ]
